[package]
name = "openapi-trait"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Generate typed Rust traits from OpenAPI specifications using a proc-macro attribute"

[dependencies]
openapi-trait-macros = { path = "../openapi-trait-macros", version = "0.1.0" }

[lints]
workspace = true
