//! Generate typed Rust traits from `OpenAPI` specifications.
//!
//! This crate exposes the [`axum`] and [`client`] attribute macros, which read
//! an `OpenAPI` specification file at compile time and generate inside the
//! annotated `mod`:
//!
//! - Rust structs for every schema defined in `components/schemas`
//! - A `{OperationId}Request` struct per operation that bundles all parameters
//!   and the request body
//! - A `{OperationId}Response` enum per operation whose variants map to HTTP
//!   status codes
//! - `impl axum::response::IntoResponse` for every response enum generated by
//!   [`axum`]
//! - A `{Title}Api` trait with one method per operation, keyed by
//!   `operationId`, generated by [`axum`]
//! - A `{Title}Client` trait with one method per operation, keyed by
//!   `operationId`, generated by [`client`]
//! - A `router` method on the trait that wires all operations to an
//!   [`axum::Router`](https://docs.rs/axum/latest/axum/struct.Router.html)
//!   when using [`axum`]
//!
//! # Quick start
//!
//! ```rust,ignore
//! #[openapi_trait::axum("openapi/petstore.yaml")]
//! pub mod petstore {}
//!
//! #[derive(Clone)]
//! struct MyServer;
//!
//! impl petstore::PetstoreApi for MyServer {
//!     type Error = std::convert::Infallible;
//!
//!     async fn list_pets(
//!         &self,
//!         req: petstore::ListPetsRequest,
//!         state: axum::extract::State<()>,
//!         headers: axum::http::HeaderMap,
//!     ) -> Result<petstore::ListPetsResponse, Self::Error> {
//!         Ok(petstore::ListPetsResponse::Status200(vec![]))
//!     }
//! }
//!
//! // Wire up an axum router.
//! let app = MyServer.router().with_state(());
//! ```
//!
//! ```rust,ignore
//! #[openapi_trait::client("openapi/petstore.yaml")]
//! pub mod petstore {}
//!
//! struct MyClient;
//!
//! impl petstore::PetstoreClient for MyClient {
//!     type Error = std::convert::Infallible;
//!
//!     async fn get_pet_by_id(
//!         &self,
//!         req: petstore::GetPetByIdRequest,
//!     ) -> Result<petstore::GetPetByIdResponse, Self::Error> {
//!         Ok(petstore::GetPetByIdResponse::Status200(petstore::Pet {
//!             id: Some(req.pet_id),
//!             name: "doggie".into(),
//!             photo_urls: vec![],
//!             category: None,
//!             tags: None,
//!             status: None,
//!         }))
//!     }
//! }
//! ```
//!
//! See the [`axum`] macro documentation for the full list of generated items
//! and compile-time error conditions.

/// The `openapi_trait` attribute macro, wired to the axum backend.
///
/// Re-exported from [`openapi_trait_axum`]. Apply it to a `mod` block with a
/// path to an `OpenAPI` YAML or JSON file. The path is resolved relative to
/// `CARGO_MANIFEST_DIR`.
#[doc(inline)]
pub use openapi_trait_axum::openapi_trait as axum;

/// The `openapi_trait` attribute macro, wired to the transport-agnostic client backend.
///
/// Re-exported from [`openapi_trait_client`]. Apply it to a `mod` block with a
/// path to an `OpenAPI` YAML or JSON file. The path is resolved relative to
/// `CARGO_MANIFEST_DIR`.
#[doc(inline)]
pub use openapi_trait_client::openapi_trait as client;
